### ISSUE TITLE
Landing Page

### ISSUE THREAD

**Issue by Nirase** [Nirase/HvZCaseFrontend#1]
## Definition of done 
The page displays a list of all the currently relevant games (Inprogress and Registration status). The user is able to see all the games without logging in, but the user has to login if they want to go to the game page for any specific game. The user is also able to login from this page. 

## TODO 

- [ ] List of games
     - [ ] Title of game
     - [ ] Date
     - [ ] Number of players in game
     - [ ]  Status
- [ ] Login button
    - [ ] Keycloak
