### ISSUE TITLE
Squad

### ISSUE THREAD

**Issue by Nirase** [Nirase/HvZCaseFrontend#10]
## Definiton
Users are able to create squads that they can communicate with and leave markers to help gather up. Within the squads there are ranks. The user can go into their squad page to see all currently alive members and all dead members. Dead members are able to see the page but can not talk or read the chat.

## TODO 
- [x] Users can create squads
- [x] Users can see squad page
- [x] Users can see currently alive members 
- [x] Users can see currently dead members 
- [x] Users can leave squad markers 
- [x] Users can leave their squad
- [ ] Users can chat within only their squad
- [x] Dead members can not see squad chat
