### ISSUE TITLE
API Calls

### ISSUE THREAD

**Issue by Nirase** [Nirase/HvZCaseFrontend#4]
## Definition of done
A service has been setup for handling calls to the API. 

## TODO
- [x] Can fetch from API 
- [x] Can post to API
- [x] Can delete from API 
- [x] Can update to API
- [x] Open API 
- [x] Closed API
